openapi: 3.0.3
info:
  title: Customer Service API
  description: API for retrieve customers data
  version: 1.0.0
  contact: {
    name: "Adrian Montenegro",
    email: "adrmontenegro97@gmail.com"
  }
servers:
  - url: http://localhost:8080/api/v1

paths:
  /customers/{uniqueCode}:
    get:
      operationId: getCustomerByUniqueCode
      summary: Get Customer by Unique Code
      parameters:
        - name: uniqueCode
          in: path
          required: true
          schema:
            type: string
      tags:
        - Customers API
      responses:
        '200':
          description: Customer found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDto'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CustomerDto:
      type: object
      properties:
        names:
          type: string
          maxLength: 500
        last_names:
          type: string
          maxLength: 500
        document_type:
          type: string
          enum:
            - DNI
            - PASS
            - CE
            - NONE
        document_number:
          type: string
          maxLength: 14
      required:
        - names
        - last_names
        - document_type
        - document_number

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
